### ISSUE TITLE
Stuck "loading" after adding project.clj

### ISSUE THREAD

**Issue by pgambling** [oakmac/cuttle#62] opened 2015-01-19 21:09 UTC
I tried to load my project.clj (uses profiles....), but the app gets stuck loading.

![loading](https://cloud.githubusercontent.com/assets/688912/5807856/e889fcc8-9fec-11e4-9068-766a8cfa614a.png)

I'm using the Mac client rc1.

**Comment by shaunlebron** [comment] 2015-01-23 05:14
The problem is that we're only looking for builds on the default profile `:dev`, which is always implicitly merged with normal config in project.clj.  Since GSO is using two custom profiles `:prod` and `:debug`, the following is not able to find the cljsbuild config:

```
$ lein pprint :cljsbuild
nil
```

We can conceivably have a dropdown for selecting profiles.  But I think for this release we should just change gso's project.clj to not use profiles.  I don't see profiles used this way in the community; sorry about that, my fault.  We can create `:prod` and `:debug` builds, and just update the aliases to use them so we don't disrupt the team's workflow.

**Comment by shaunlebron** [comment] 2015-01-27 09:49
fixed so that it warns the user if no cljsbuild config was found for the project instead of hanging at the loading status.

**Closed by shaunlebron** 2015-01-27 09:49 UTC
Labels: bug
